"""add chat_conditions

Revision ID: 11190055d2ac
Revises: 8302a8f97738
Create Date: 2023-09-24 00:27:56.614795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11190055d2ac'
down_revision = '8302a8f97738'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('raw_conditions', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('parsed_conditions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'parsed_conditions')
    op.drop_column('chats', 'raw_conditions')
    # ### end Alembic commands ###
